# Generated by Django 5.0.6 on 2024-06-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Pet',
        ),
    ]
